import json, os

BASE = os.path.dirname(os.path.abspath(__file__))

# ======================================================================
# Helpers
# ======================================================================
def cell(source_lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source_lines
    }

META = {
    "kernelspec": {"display_name": "Python 3", "name": "python3"},
    "language_info": {"name": "python"},
    "colab": {"provenance": []}
}

# ======================================================================
# BLUE notebook  —  forge_grpo_colab.ipynb
# ======================================================================
blue_cells = [
    cell([
        "# Cell 1 — Install\n",
        "!pip install -q \"openenv-core[core]>=0.2.1\"\n",
        "!pip install -q \"unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git\"\n",
        "!pip install -q trl transformers datasets accelerate peft\n",
        "!pip install -q torch-geometric\n",
        "!git clone https://huggingface.co/spaces/NeuralHU/forge-rl /content/forge-rl\n",
        "\n",
        "import sys, os, torch\n",
        "sys.path.insert(0, '/content/forge-rl')\n",
        "os.chdir('/content/forge-rl')\n",
        "\n",
        "if not torch.cuda.is_available():\n",
        "    raise RuntimeError('NO GPU DETECTED. Runtime -> Change runtime type -> T4 GPU')\n",
        "print(f'GPU: {torch.cuda.get_device_name(0)}')\n",
        "print('Setup complete.')",
    ]),
    cell([
        "# Cell 2 — Load model\n",
        "from unsloth import FastLanguageModel\n",
        "\n",
        "model, tokenizer = FastLanguageModel.from_pretrained(\n",
        "    model_name='unsloth/Qwen2.5-3B-Instruct',\n",
        "    max_seq_length=1024,\n",
        "    load_in_4bit=True,\n",
        "    dtype=None,\n",
        ")\n",
        "model = FastLanguageModel.get_peft_model(\n",
        "    model,\n",
        "    r=16, lora_alpha=16,\n",
        "    target_modules=['q_proj', 'k_proj', 'v_proj', 'o_proj'],\n",
        "    lora_dropout=0, bias='none',\n",
        "    use_gradient_checkpointing='unsloth',\n",
        ")\n",
        "print('Model loaded.')",
    ]),
    cell([
        "# Cell 3 — Reward function\n",
        "import numpy as np\n",
        "from env.forge_env import ForgeEnv, ForgeEnvConfig\n",
        "\n",
        "TOOL_ACTIONS = [0, 5, 2]  # query_source, temporal_audit, cross_reference\n",
        "\n",
        "def _parse_verdict(text):\n",
        "    t = text.lower()\n",
        "    if any(w in t for w in ['fabricat']): return 12\n",
        "    if any(w in t for w in ['out of context', 'recontextual', 'cropped']): return 11\n",
        "    if any(w in t for w in ['satire', 'parody', 'joke']): return 10\n",
        "    if any(w in t for w in ['misinfo', 'false', 'manipulat', 'mislead']): return 9\n",
        "    if any(w in t for w in ['verified', 'true', 'legitimate', 'accurate']): return 8\n",
        "    return 9\n",
        "\n",
        "def _safe_step(env, action):\n",
        "    result = env.step(action)\n",
        "    if isinstance(result, tuple):\n",
        "        if len(result) == 5:\n",
        "            _, reward, terminated, truncated, _ = result\n",
        "            return float(reward), bool(terminated or truncated)\n",
        "        elif len(result) == 4:\n",
        "            _, reward, terminated, _ = result\n",
        "            return float(reward), bool(terminated)\n",
        "        elif len(result) == 2:\n",
        "            _, reward = result\n",
        "            return float(reward), False\n",
        "    return float(getattr(result, 'reward', 0.0)), bool(getattr(result, 'done', False))\n",
        "\n",
        "def _safe_reset(env):\n",
        "    result = env.reset()\n",
        "    if isinstance(result, tuple) and len(result) == 2:\n",
        "        return result\n",
        "    return result, {}\n",
        "\n",
        "def reward_fn(prompts, completions, claim_texts=None, **kwargs):\n",
        "    rewards = []\n",
        "    for i, completion in enumerate(completions):\n",
        "        comp_text = (completion[-1]['content'] if isinstance(completion, list) else str(completion))\n",
        "        try:\n",
        "            cfg = ForgeEnvConfig(budget=6, seed=42 + i)\n",
        "            env = ForgeEnv(cfg)\n",
        "            obs, info = _safe_reset(env)\n",
        "            if claim_texts and i < len(claim_texts):\n",
        "                for attr in ('_claim_text', '_claim_text_initial'):\n",
        "                    if hasattr(env, attr): setattr(env, attr, claim_texts[i])\n",
        "            done = False\n",
        "            for act in TOOL_ACTIONS:\n",
        "                if done: break\n",
        "                _, done = _safe_step(env, act)\n",
        "            verdict_action = _parse_verdict(comp_text)\n",
        "            reward, _ = _safe_step(env, verdict_action)\n",
        "            rewards.append(float(np.clip(reward, 0.001, 0.999)))\n",
        "        except Exception as e:\n",
        "            print(f'[reward_fn] episode {i} error: {e}')\n",
        "            rewards.append(0.001)\n",
        "    return rewards\n",
        "\n",
        "print('reward_fn ready.')",
    ]),
    cell([
        "# Cell 4 — Dataset\n",
        "from datasets import Dataset\n",
        "import random\n",
        "\n",
        "PROMPT_TMPL = ('You are a misinformation forensics agent. Investigate the claim:\\n'\n",
        "               'CLAIM: {claim}\\n\\n'\n",
        "               'Submit your verdict:\\n'\n",
        "               '- \"This is MISINFO because [reason]\"\\n'\n",
        "               '- \"This is SATIRE because [reason]\"\\n'\n",
        "               '- \"This is VERIFIED because [reason]\"\\n'\n",
        "               '- \"This is FABRICATED because [reason]\"\\n'\n",
        "               '- \"This is OUT OF CONTEXT because [reason]\"\\n'\n",
        "               'Your verdict:')\n",
        "\n",
        "TASK_NAMES = ['fabricated_stats', 'out_of_context', 'coordinated_campaign',\n",
        "              'satire_news', 'verified_fact', 'politifact_liar',\n",
        "              'image_forensics', 'sec_fraud']\n",
        "\n",
        "def _get_claim(task, seed):\n",
        "    try:\n",
        "        cfg = ForgeEnvConfig(budget=3, seed=seed)\n",
        "        env = ForgeEnv(cfg)\n",
        "        _, info = _safe_reset(env)\n",
        "        for attr in ('_claim_text', 'claim_text'):\n",
        "            val = getattr(env, attr, None)\n",
        "            if val: return str(val)\n",
        "        if info and 'claim_text' in info: return info['claim_text']\n",
        "    except: pass\n",
        "    return f'Unverified claim #{seed} in domain: {task}'\n",
        "\n",
        "random.seed(42)\n",
        "claims, prompts = [], []\n",
        "for i in range(200):\n",
        "    claim = _get_claim(TASK_NAMES[i % len(TASK_NAMES)], seed=i)\n",
        "    claims.append(claim)\n",
        "    prompts.append([{'role': 'user', 'content': PROMPT_TMPL.format(claim=claim)}])\n",
        "\n",
        "dataset = Dataset.from_dict({'prompt': prompts, 'claim_texts': claims})\n",
        "print(f'Dataset: {len(dataset)} rows')",
    ]),
    cell([
        "# Cell 5 — Baseline\n",
        "def evaluate_heuristic(n_episodes=20, default_verdict=9):\n",
        "    rewards, correct = [], 0\n",
        "    for i in range(n_episodes):\n",
        "        try:\n",
        "            env = ForgeEnv(ForgeEnvConfig(budget=6, seed=100 + i))\n",
        "            _safe_reset(env)\n",
        "            done = False\n",
        "            for act in TOOL_ACTIONS:\n",
        "                if done: break\n",
        "                _, done = _safe_step(env, act)\n",
        "            reward, _ = _safe_step(env, default_verdict)\n",
        "            rewards.append(float(reward))\n",
        "            if reward > 0.5: correct += 1\n",
        "        except Exception as e:\n",
        "            print(f'Eval error ep {i}: {e}')\n",
        "            rewards.append(0.001)\n",
        "    return float(np.mean(rewards)), correct / n_episodes\n",
        "\n",
        "baseline_reward, baseline_acc = evaluate_heuristic()\n",
        "print(f'HEURISTIC BASELINE — reward: {baseline_reward:.4f} | acc: {baseline_acc:.2%}')",
    ]),
    cell([
        "# Cell 6 — GRPO Training\n",
        "from trl import GRPOConfig, GRPOTrainer\n",
        "\n",
        "config = GRPOConfig(\n",
        "    output_dir='./forge-grpo',\n",
        "    max_steps=150,\n",
        "    num_generations=4,\n",
        "    max_completion_length=128,\n",
        "    per_device_train_batch_size=1,\n",
        "    gradient_accumulation_steps=8,\n",
        "    learning_rate=5e-6,\n",
        "    save_steps=50,\n",
        "    logging_steps=5,\n",
        "    report_to='none',\n",
        "    warmup_ratio=0.1,\n",
        ")\n",
        "\n",
        "try:\n",
        "    trainer = GRPOTrainer(model=model, reward_funcs=reward_fn, args=config,\n",
        "                          train_dataset=dataset, processing_class=tokenizer)\n",
        "except TypeError:\n",
        "    trainer = GRPOTrainer(model=model, reward_funcs=reward_fn, args=config,\n",
        "                          train_dataset=dataset, tokenizer=tokenizer)\n",
        "\n",
        "print('Starting GRPO training (max 150 steps ~45 min on T4)...')\n",
        "trainer.train()\n",
        "print('Training complete.')",
    ]),
    cell([
        "# Cell 7 — Evaluation + plots\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib; matplotlib.use('Agg')\n",
        "import os\n",
        "os.makedirs('results', exist_ok=True)\n",
        "\n",
        "def evaluate_trained(n_episodes=20):\n",
        "    rewards, correct = [], 0\n",
        "    FastLanguageModel.for_inference(model)\n",
        "    for i in range(n_episodes):\n",
        "        try:\n",
        "            claim = _get_claim(TASK_NAMES[i % len(TASK_NAMES)], seed=200 + i)\n",
        "            prompt_ids = tokenizer.apply_chat_template(\n",
        "                [{'role': 'user', 'content': PROMPT_TMPL.format(claim=claim)}],\n",
        "                tokenize=True, return_tensors='pt', add_generation_prompt=True,\n",
        "            ).to('cuda')\n",
        "            outputs = model.generate(input_ids=prompt_ids, max_new_tokens=80,\n",
        "                                     temperature=0.3, do_sample=True)\n",
        "            response = tokenizer.decode(outputs[0][prompt_ids.shape[1]:], skip_special_tokens=True)\n",
        "            env = ForgeEnv(ForgeEnvConfig(budget=6, seed=200 + i))\n",
        "            _safe_reset(env)\n",
        "            done = False\n",
        "            for act in TOOL_ACTIONS:\n",
        "                if done: break\n",
        "                _, done = _safe_step(env, act)\n",
        "            reward, _ = _safe_step(env, _parse_verdict(response))\n",
        "            rewards.append(float(reward))\n",
        "            if reward > 0.5: correct += 1\n",
        "        except Exception as e:\n",
        "            print(f'Trained eval error ep {i}: {e}')\n",
        "            rewards.append(0.001)\n",
        "    return float(np.mean(rewards)), correct / n_episodes\n",
        "\n",
        "trained_reward, trained_acc = evaluate_trained()\n",
        "print(f'BASELINE — {baseline_reward:.4f} | {baseline_acc:.2%}')\n",
        "print(f'TRAINED  — {trained_reward:.4f} | {trained_acc:.2%}')\n",
        "print(f'DELTA    — {trained_reward - baseline_reward:+.4f} | {trained_acc - baseline_acc:+.2%}')\n",
        "\n",
        "steps, rew = [], []\n",
        "for l in trainer.state.log_history:\n",
        "    for key in ('rewards/mean', 'reward/mean', 'reward'):\n",
        "        if key in l:\n",
        "            steps.append(l['step']); rew.append(l[key]); break\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(10, 5))\n",
        "if steps: ax.plot(steps, rew, 'b-', linewidth=2.5, label='Training reward')\n",
        "ax.axhline(y=baseline_reward, color='r', linestyle='--', linewidth=2,\n",
        "           label=f'Heuristic baseline ({baseline_reward:.3f})')\n",
        "ax.set_xlabel('Training Step'); ax.set_ylabel('Mean Episode Reward')\n",
        "ax.set_title('FORGE-MA: LLM Agent Learning Misinformation Detection via GRPO')\n",
        "ax.legend(); ax.grid(True, alpha=0.3); ax.set_ylim(0, 1.0)\n",
        "plt.tight_layout()\n",
        "plt.savefig('results/reward_curve.png', dpi=150, bbox_inches='tight')\n",
        "plt.close()\n",
        "print('Saved: results/reward_curve.png')",
    ]),
]

nb_blue = {"cells": blue_cells, "metadata": META, "nbformat": 4, "nbformat_minor": 0}
path_blue = os.path.join(BASE, "training", "forge_grpo_colab.ipynb")
with open(path_blue, "w", encoding="utf-8") as f:
    json.dump(nb_blue, f, indent=2, ensure_ascii=False)
print(f"Written: {path_blue}")

# ======================================================================
# RED notebook  —  red_grpo_colab.ipynb
# ======================================================================
red_cells = [
    cell([
        "# Cell 1 — Install\n",
        "!pip install -q \"openenv-core[core]>=0.2.1\"\n",
        "!pip install -q \"unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git\"\n",
        "!pip install -q trl transformers datasets accelerate peft\n",
        "!pip install -q torch-geometric\n",
        "!git clone https://huggingface.co/spaces/NeuralHU/forge-rl /content/forge-rl\n",
        "\n",
        "import sys, os, torch\n",
        "sys.path.insert(0, '/content/forge-rl')\n",
        "os.chdir('/content/forge-rl')\n",
        "\n",
        "if not torch.cuda.is_available():\n",
        "    raise RuntimeError('NO GPU DETECTED. Runtime -> Change runtime type -> T4 GPU')\n",
        "print(f'GPU: {torch.cuda.get_device_name(0)}')\n",
        "print('Setup complete.')",
    ]),
    cell([
        "# Cell 2 — Load model\n",
        "from unsloth import FastLanguageModel\n",
        "\n",
        "model, tokenizer = FastLanguageModel.from_pretrained(\n",
        "    model_name='unsloth/Qwen2.5-3B-Instruct',\n",
        "    max_seq_length=1024,\n",
        "    load_in_4bit=True,\n",
        "    dtype=None,\n",
        ")\n",
        "model = FastLanguageModel.get_peft_model(\n",
        "    model,\n",
        "    r=16, lora_alpha=16,\n",
        "    target_modules=['q_proj', 'k_proj', 'v_proj', 'o_proj'],\n",
        "    lora_dropout=0, bias='none',\n",
        "    use_gradient_checkpointing='unsloth',\n",
        ")\n",
        "print('Red model loaded.')",
    ]),
    cell([
        "# Cell 3 — Red reward function (maximize Blue TED)\n",
        "import numpy as np\n",
        "from env.forge_env import ForgeEnv, ForgeEnvConfig\n",
        "from rewards.tactic_edit_dist import tactic_edit_distance\n",
        "from env.primitives import PrimitiveType\n",
        "\n",
        "RED_PROMPT = ('You are a RED TEAM adversarial agent. Your goal is to craft a '\n",
        "              'misinformation chain that defeats Blue Team forensic detection.\\n'\n",
        "              'Use these primitives: SOURCE_LAUNDER, TEMPORAL_SHIFT, '\n",
        "              'ENTITY_SUBSTITUTE, QUOTE_FABRICATE, CONTEXT_STRIP, '\n",
        "              'CITATION_FORGE, NETWORK_AMPLIFY, SATIRE_REFRAME\\n\\n'\n",
        "              'Claim: {claim}\\n\\n'\n",
        "              'Output a chain of 2-4 primitives that will evade detection:')\n",
        "\n",
        "PRIMITIVE_NAMES = [p.value for p in PrimitiveType]\n",
        "\n",
        "def _extract_chain(text):\n",
        "    found = []\n",
        "    for name in PRIMITIVE_NAMES:\n",
        "        if name in text.upper():\n",
        "            found.append(name)\n",
        "    return found[:4]\n",
        "\n",
        "def _safe_step(env, action):\n",
        "    result = env.step(action)\n",
        "    if isinstance(result, tuple):\n",
        "        if len(result) == 5:\n",
        "            _, reward, terminated, truncated, _ = result\n",
        "            return float(reward), bool(terminated or truncated)\n",
        "        elif len(result) == 4:\n",
        "            _, reward, terminated, _ = result\n",
        "            return float(reward), bool(terminated)\n",
        "        elif len(result) == 2:\n",
        "            _, reward = result\n",
        "            return float(reward), False\n",
        "    return float(getattr(result, 'reward', 0.0)), bool(getattr(result, 'done', False))\n",
        "\n",
        "def _safe_reset(env):\n",
        "    result = env.reset()\n",
        "    if isinstance(result, tuple) and len(result) == 2:\n",
        "        return result\n",
        "    return result, {}\n",
        "\n",
        "def red_reward_fn(prompts, completions, true_chains=None, **kwargs):\n",
        "    rewards = []\n",
        "    for i, completion in enumerate(completions):\n",
        "        text = (completion[-1]['content'] if isinstance(completion, list) else str(completion))\n",
        "        try:\n",
        "            predicted = _extract_chain(text)\n",
        "            true = true_chains[i] if true_chains and i < len(true_chains) else []\n",
        "            # Red reward = TED (high TED = Blue agent confused)\n",
        "            ted = tactic_edit_distance(predicted, true)\n",
        "            rewards.append(float(np.clip(ted, 0.001, 0.999)))\n",
        "        except Exception as e:\n",
        "            print(f'[red_reward_fn] episode {i} error: {e}')\n",
        "            rewards.append(0.001)\n",
        "    return rewards\n",
        "\n",
        "print('red_reward_fn ready.')",
    ]),
    cell([
        "# Cell 4 — Dataset\n",
        "from datasets import Dataset\n",
        "import random\n",
        "\n",
        "TASK_NAMES = ['fabricated_stats', 'out_of_context', 'coordinated_campaign',\n",
        "              'satire_news', 'verified_fact', 'politifact_liar',\n",
        "              'image_forensics', 'sec_fraud']\n",
        "\n",
        "def _get_claim_and_chain(task, seed):\n",
        "    try:\n",
        "        env = ForgeEnv(ForgeEnvConfig(budget=3, seed=seed))\n",
        "        _, info = _safe_reset(env)\n",
        "        claim = None\n",
        "        for attr in ('_claim_text', 'claim_text'):\n",
        "            val = getattr(env, attr, None)\n",
        "            if val: claim = str(val); break\n",
        "        if claim is None and info:\n",
        "            claim = info.get('claim_text', f'Claim #{seed}')\n",
        "        true_chain = [str(p.value) if hasattr(p, 'value') else str(p)\n",
        "                      for p in info.get('true_chain', [])] if info else []\n",
        "        return claim or f'Claim #{seed}', true_chain\n",
        "    except:\n",
        "        return f'Unverified claim #{seed} in domain: {task}', []\n",
        "\n",
        "random.seed(42)\n",
        "prompts, true_chains = [], []\n",
        "for i in range(200):\n",
        "    claim, chain = _get_claim_and_chain(TASK_NAMES[i % len(TASK_NAMES)], seed=i)\n",
        "    prompts.append([{'role': 'user', 'content': RED_PROMPT.format(claim=claim)}])\n",
        "    true_chains.append(chain)\n",
        "\n",
        "dataset = Dataset.from_dict({'prompt': prompts, 'true_chains': true_chains})\n",
        "print(f'Red dataset: {len(dataset)} rows')",
    ]),
    cell([
        "# Cell 5 — GRPO Training (Red)\n",
        "from trl import GRPOConfig, GRPOTrainer\n",
        "\n",
        "config = GRPOConfig(\n",
        "    output_dir='./red-grpo',\n",
        "    max_steps=150,\n",
        "    num_generations=4,\n",
        "    max_completion_length=128,\n",
        "    per_device_train_batch_size=1,\n",
        "    gradient_accumulation_steps=8,\n",
        "    learning_rate=5e-6,\n",
        "    save_steps=50,\n",
        "    logging_steps=5,\n",
        "    report_to='none',\n",
        "    warmup_ratio=0.1,\n",
        ")\n",
        "\n",
        "try:\n",
        "    trainer = GRPOTrainer(model=model, reward_funcs=red_reward_fn, args=config,\n",
        "                          train_dataset=dataset, processing_class=tokenizer)\n",
        "except TypeError:\n",
        "    trainer = GRPOTrainer(model=model, reward_funcs=red_reward_fn, args=config,\n",
        "                          train_dataset=dataset, tokenizer=tokenizer)\n",
        "\n",
        "print('Starting Red GRPO training (max 150 steps)...')\n",
        "trainer.train()\n",
        "print('Training complete.')",
    ]),
    cell([
        "# Cell 6 — Plot\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib; matplotlib.use('Agg')\n",
        "import os\n",
        "os.makedirs('results', exist_ok=True)\n",
        "\n",
        "steps, rew = [], []\n",
        "for l in trainer.state.log_history:\n",
        "    for key in ('rewards/mean', 'reward/mean', 'reward'):\n",
        "        if key in l:\n",
        "            steps.append(l['step']); rew.append(l[key]); break\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(10, 5))\n",
        "if steps: ax.plot(steps, rew, 'r-', linewidth=2.5, label='Red TED reward')\n",
        "ax.set_xlabel('Training Step'); ax.set_ylabel('Mean TED Reward')\n",
        "ax.set_title('FORGE-MA: Red Team Adversarial Training via GRPO')\n",
        "ax.legend(); ax.grid(True, alpha=0.3); ax.set_ylim(0, 1.0)\n",
        "plt.tight_layout()\n",
        "plt.savefig('results/red_reward_curve.png', dpi=150, bbox_inches='tight')\n",
        "plt.close()\n",
        "print('Saved: results/red_reward_curve.png')",
    ]),
]

nb_red = {"cells": red_cells, "metadata": META, "nbformat": 4, "nbformat_minor": 0}
path_red = os.path.join(BASE, "training", "red_grpo_colab.ipynb")
with open(path_red, "w", encoding="utf-8") as f:
    json.dump(nb_red, f, indent=2, ensure_ascii=False)
print(f"Written: {path_red}")

# Verify
for path in [path_blue, path_red]:
    with open(path, encoding="utf-8") as f:
        txt = f.read()
    ok = "NeuralHU/forge-rl" in txt and "YOUR_USERNAME" not in txt
    print(f"{'OK' if ok else 'FAIL'}: {os.path.basename(path)}")
